"""
Content-based recommendation engine using semantic embeddings.

Encodes product descriptions with a SentenceTransformer model and
recommends similar products based on cosine similarity between
their embedding vectors.
"""

from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity


class ContentBasedRecommender:
    """
    Content-based recommender using semantic product embeddings.

    Products are represented by dense vectors computed from their text
    descriptions. Recommendations are generated by finding the most
    similar products via cosine similarity.
    """

    def __init__(
        self,
        model_name: str = "all-MiniLM-L6-v2",
    ):
        """
        Initialize the content-based recommender.

        Args:
            model_name: Name of the SentenceTransformer model to use
                       for encoding product descriptions.
        """
        self.model_name = model_name
        self._model = None
        self.product_embeddings: Optional[np.ndarray] = None
        self.product_ids: List[str] = []
        self.product_metadata: Dict[str, Dict] = {}
        self.similarity_matrix: Optional[np.ndarray] = None

    def _get_model(self):
        """Lazy-load the SentenceTransformer model."""
        if self._model is None:
            from sentence_transformers import SentenceTransformer

            self._model = SentenceTransformer(self.model_name)
        return self._model

    def fit(
        self,
        products: pd.DataFrame,
        id_col: str = "product_id",
        text_col: str = "description",
        metadata_cols: Optional[List[str]] = None,
    ) -> None:
        """
        Build the product embedding matrix from a product catalog.

        Args:
            products: DataFrame with product information.
            id_col: Column name containing product IDs.
            text_col: Column name containing text to encode.
            metadata_cols: Additional columns to store as metadata
                          (e.g., name, category, price).
        """
        if metadata_cols is None:
            metadata_cols = ["name", "category", "price"]

        self.product_ids = products[id_col].astype(str).tolist()

        # Store metadata for each product
        available_meta = [c for c in metadata_cols if c in products.columns]
        for _, row in products.iterrows():
            pid = str(row[id_col])
            self.product_metadata[pid] = {
                col: row[col] for col in available_meta if pd.notna(row[col])
            }

        # Encode product descriptions
        descriptions = products[text_col].fillna("").tolist()
        model = self._get_model()
        self.product_embeddings = model.encode(
            descriptions,
            show_progress_bar=True,
            normalize_embeddings=True,
        )

        # Precompute similarity matrix for fast lookups
        self.similarity_matrix = cosine_similarity(self.product_embeddings)

        print(
            f"Indexed {len(self.product_ids)} products with "
            f"{self.product_embeddings.shape[1]}-dimensional embeddings"
        )

    def recommend_similar(
        self,
        product_id: str,
        n: int = 10,
        exclude_self: bool = True,
    ) -> List[Dict]:
        """
        Recommend products similar to a given product.

        Args:
            product_id: The ID of the reference product.
            n: Number of recommendations to return.
            exclude_self: Whether to exclude the input product from results.

        Returns:
            List of dicts with product_id, score, and metadata for each
            recommended product, sorted by similarity descending.
        """
        if self.similarity_matrix is None:
            raise RuntimeError("Model not fitted. Call fit() first.")

        if product_id not in self.product_ids:
            raise ValueError(f"Product '{product_id}' not found in index.")

        idx = self.product_ids.index(product_id)
        similarities = self.similarity_matrix[idx]

        # Get top-N indices (excluding self if requested)
        sorted_indices = np.argsort(similarities)[::-1]

        recommendations = []
        for i in sorted_indices:
            if exclude_self and i == idx:
                continue
            if len(recommendations) >= n:
                break

            pid = self.product_ids[i]
            recommendations.append(
                {
                    "product_id": pid,
                    "score": round(float(similarities[i]), 4),
                    **self.product_metadata.get(pid, {}),
                }
            )

        return recommendations

    def recommend_by_text(
        self,
        query_text: str,
        n: int = 10,
    ) -> List[Dict]:
        """
        Recommend products similar to an arbitrary text query.

        Useful for search-like recommendations ("I want something
        like a red winter jacket").

        Args:
            query_text: Free-text description of desired products.
            n: Number of recommendations to return.

        Returns:
            List of recommendation dicts sorted by similarity.
        """
        if self.product_embeddings is None:
            raise RuntimeError("Model not fitted. Call fit() first.")

        model = self._get_model()
        query_embedding = model.encode(
            [query_text], normalize_embeddings=True
        )

        similarities = cosine_similarity(
            query_embedding, self.product_embeddings
        )[0]

        sorted_indices = np.argsort(similarities)[::-1][:n]

        recommendations = []
        for i in sorted_indices:
            pid = self.product_ids[i]
            recommendations.append(
                {
                    "product_id": pid,
                    "score": round(float(similarities[i]), 4),
                    **self.product_metadata.get(pid, {}),
                }
            )

        return recommendations

    def get_embedding(self, product_id: str) -> Optional[np.ndarray]:
        """
        Get the embedding vector for a specific product.

        Args:
            product_id: The product ID.

        Returns:
            Embedding vector as numpy array, or None if not found.
        """
        if product_id not in self.product_ids:
            return None

        idx = self.product_ids.index(product_id)
        return self.product_embeddings[idx]
